name: Docker Image CI/CD for Product Service - Create

on:
  push:
    paths:
      - 'catalog/readProductService/**'
    branches: ["test"]
  pull_request:
    paths:
      - 'catalog/readProductService/**'
    branches: ["QA", "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Login en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Paso 3: Construir la imagen Docker usando los secrets
    - name: Build Docker image
      run: |
        docker build catalog/readProductService/. --file catalog/readProductService/Dockerfile \
          --build-arg MONGO_URI=${{ secrets.MONGO_URI }} \
          --build-arg DB_NAME=${{ secrets.DB_NAME }} \
          --build-arg SERVER_PORT=${{ secrets.SERVER_PORT }} \
          -t ${{ secrets.DOCKER_USERNAME }}/read-product-service:latest .

    # Paso 4: Subir la imagen a Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/read-product-service:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Conectar al servidor EC2 usando SSH
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST_CREATE_PRODUCT }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          echo "Deteniendo y eliminando contenedor previo..."
          docker stop read-product-service || true
          docker rm read-product-service || true
          
          echo "Actualizando imagen desde Docker Hub..."
          docker pull ${{ secrets.DOCKER_USERNAME }}/read-product-service:latest
          
          echo "Ejecutando nuevo contenedor en el puerto 80..."
          docker run -d \
            --name read-product-service \
            -p 80:${{ secrets.SERVER_PORT_CREATE_PRODUCT }} \
            -e MONGO_URI=${{ secrets.MONGO_URI }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e SERVER_PORT=${{ secrets.SERVER_PORT }} \
            ${{ secrets.DOCKER_USERNAME }}/read-product-service:latest
