name: Docker Image CI/CD for Login Service

on:
  push:
    paths:
      - 'user/login/**'
    branches: [ "test" ]
  pull_request:
    paths:
      - 'user/login/**'
    branches: 
      - "QA"
      - "main"

jobs:
  build-and-push:
    name: Build, Package, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar variables de entorno desde el archivo .env
      - name: Load environment variables
        run: |
          cp user/login/.env .env
          echo "Environment variables loaded:"
          cat .env
        env:
          APP_NAME: ${{ secrets.APP_NAME_LOGIN }}
          SERVER_PORT: ${{ secrets.SERVER_PORT_LOGIN }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DRIVER: ${{ secrets.DB_DRIVER }}
          DB_CONNECTION_TIMEOUT: ${{ secrets.DB_CONNECTION_TIMEOUT }}
          DB_MAX_POOL_SIZE: ${{ secrets.DB_MAX_POOL_SIZE }}
          JPA_DDL_AUTO: ${{ secrets.JPA_DDL_AUTO }}
          JPA_SHOW_SQL: ${{ secrets.JPA_SHOW_SQL }}
          JPA_OPEN_IN_VIEW: ${{ secrets.JPA_OPEN_IN_VIEW }}
          JPA_DATABASE_PLATFORM: ${{ secrets.JPA_DATABASE_PLATFORM }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
          DOMINIO_URL: ${{ secrets.DOMINIO_URL }}

      # 3. Instalar JDK y Maven
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Construir el archivo .jar con Maven
      - name: Build .jar file
        run: mvn clean install -f user/login/pom.xml

      # 5. Log in en DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Construir y subir la imagen Docker a DockerHub
      - name: Build and push Docker image
        run: |
          docker build user/login/. --file user/login/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/login-service:${{ env.version_tag }} --tag ${{ secrets.DOCKER_USERNAME }}/login-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/login-service:${{ env.version_tag }}
          docker push ${{ secrets.DOCKER_USERNAME }}/login-service:latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # 1. Conectar a EC2 y desplegar la aplicación
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
                # Actualizar y configurar Docker
                sudo yum update -y
                sudo yum install -y docker
                sudo service docker start
                sudo usermod -a -G docker ec2-user
              
                # Descargar la imagen Docker desde DockerHub
                sudo docker pull ${{ secrets.DOCKER_USERNAME }}/login-service:latest
              
                # Detener y eliminar cualquier contenedor existente con el nombre "login-service"
                if [ $(sudo docker ps -aq -f name=login-service) ]; then
                  sudo docker stop login-service
                  sudo docker rm login-service
                fi
              
                # Iniciar un nuevo contenedor con la imagen más reciente
                sudo docker run -d --name login-service -p 80:80 ${{ secrets.DOCKER_USERNAME }}/login-service:latest
