name: Docker Image CI/CD for Login Service

on:
  push:
    paths:
      - 'user/login/**'
    branches: [ "test" ]
  pull_request:
    paths:
      - 'user/login/**'
    branches: 
      - "QA"
      - "main"

jobs:
  build-and-push:
    name: Build, Package, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del c칩digo fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar variables de entorno desde el archivo .env
      - name: Create .env file
        run: |
          echo "APP_NAME=${{ secrets.APP_NAME_LOGIN }}" >> .env
          echo "SERVER_PORT=${{ secrets.SERVER_PORT_LOGIN }}" >> .env
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_DRIVER=${{ secrets.DB_DRIVER }}" >> .env
          echo "DB_CONNECTION_TIMEOUT=${{ secrets.DB_CONNECTION_TIMEOUT }}" >> .env
          echo "DB_MAX_POOL_SIZE=${{ secrets.DB_MAX_POOL_SIZE }}" >> .env
          echo "JPA_DDL_AUTO=${{ secrets.JPA_DDL_AUTO }}" >> .env
          echo "JPA_SHOW_SQL=${{ secrets.JPA_SHOW_SQL }}" >> .env
          echo "JPA_OPEN_IN_VIEW=${{ secrets.JPA_OPEN_IN_VIEW }}" >> .env
          echo "JPA_DATABASE_PLATFORM=${{ secrets.JPA_DATABASE_PLATFORM }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}" >> .env
          echo "DOMINIO_URL=${{ secrets.DOMINIO_URL }}" >> .env

      # 3. Instalar JDK y Maven
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Construir el archivo .jar con Maven
      - name: Build .jar file
        run: mvn clean install -f user/login/pom.xml

      # 5. Log in en DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Construir y subir la imagen Docker a DockerHub
      - name: Build and push Docker image
        run: |
          docker build user/login/. --file user/login/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/login-service:${{ env.version_tag }} --tag ${{ secrets.DOCKER_USERNAME }}/login-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/login-service:${{ env.version_tag }}
          docker push ${{ secrets.DOCKER_USERNAME }}/login-service:latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # 1. Conectar a EC2 y desplegar la aplicaci칩n
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Actualizar y configurar Docker
            sudo yum update -y
            sudo yum install -y docker
            sudo service docker start
            sudo usermod -a -G docker ec2-user
          
            # Descargar la imagen Docker desde DockerHub
            echo "==> Pulling the latest Docker image"
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/login-service:latest
          
            # Verificar si el contenedor existe
            if [ $(sudo docker ps -aq -f name=login-service) ]; then
              echo "==> Stopping and removing existing container"
              sudo docker stop login-service || echo "Failed to stop container, possibly not running."
              sudo docker rm login-service || echo "Failed to remove container, ensure it is stopped."
            else
              echo "==> No existing container found with the name 'login-service'"
            fi
          
            # Iniciar un nuevo contenedor con la imagen m치s reciente
            echo "==> Starting a new container"
            sudo docker run -d --name login-service -p 80:80 ${{ secrets.DOCKER_USERNAME }}/login-service:latest
          
            # Verificar si el contenedor est치 corriendo
            if sudo docker ps -f name=login-service | grep login-service; then
              echo "==> Container started successfully"
            else
              echo "==> Failed to start the container. Check the Docker logs for details."
              exit 1
            fi
